/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectopokemon;

/**
 *
 * @author LCE 2-13
 */
public class SeleccionPokemon extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionPokemon
     */
    public SeleccionPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        BotonFinalizar = new javax.swing.JButton();
        Umbreon = new javax.swing.JCheckBox();
        SkarmoryIMG = new javax.swing.JLabel();
        Skarmory = new javax.swing.JCheckBox();
        RaikouIMG = new javax.swing.JLabel();
        Raikou = new javax.swing.JCheckBox();
        GardevoirIMG = new javax.swing.JLabel();
        Gardevoir = new javax.swing.JCheckBox();
        CacturneIMG = new javax.swing.JLabel();
        Cacturne = new javax.swing.JCheckBox();
        UmbreonIMG = new javax.swing.JLabel();
        Charizard = new javax.swing.JCheckBox();
        BlazikenIMG = new javax.swing.JLabel();
        Blaziken = new javax.swing.JCheckBox();
        PiplupIMG = new javax.swing.JLabel();
        Piplup = new javax.swing.JCheckBox();
        SnorlaxIMG = new javax.swing.JLabel();
        Snorlax = new javax.swing.JCheckBox();
        VaporeonIMG = new javax.swing.JLabel();
        Vaporeon = new javax.swing.JCheckBox();
        CharizardIMG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ELIGE 3 POKEMONES");

        BotonFinalizar.setText("FINALIZAR");

        Umbreon.setText("UMBREON");

        SkarmoryIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/skarmory_fixed.gif"))); // NOI18N

        Skarmory.setText("SKARMORY");
        Skarmory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkarmoryActionPerformed(evt);
            }
        });

        RaikouIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/raikou_fixed.gif"))); // NOI18N

        Raikou.setText("RAIKOU");
        Raikou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaikouActionPerformed(evt);
            }
        });

        GardevoirIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/gardevoir_fixed.gif"))); // NOI18N

        Gardevoir.setText("GARDEVOIR");

        CacturneIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/cacturne_fixed.gif"))); // NOI18N

        Cacturne.setText("CACTURNE");

        UmbreonIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/umbreon_fixed.gif"))); // NOI18N

        Charizard.setText("CHARIZARD");

        BlazikenIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/blaziken_fixed.gif"))); // NOI18N

        Blaziken.setText("BLAZIKEN");

        PiplupIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/piplup_fixed.gif"))); // NOI18N

        Piplup.setText("PIPLUP");
        Piplup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiplupActionPerformed(evt);
            }
        });

        SnorlaxIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/snorlax_fixed.gif"))); // NOI18N

        Snorlax.setText("SNORLAX");

        VaporeonIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/vaporeon_fixed.gif"))); // NOI18N

        Vaporeon.setText("VAPOREON");

        CharizardIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopokemon/Imagenes/gifs_fixed/charizard_fixed.gif"))); // NOI18N

        jMenu2.setText("ELIGE TU POKEMON");

        jMenu6.setText("File");
        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ELIGE TU PERSONAJE");

        jMenu4.setText("File");
        jMenu3.add(jMenu4);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("ELIGE EL ORDEN DE TUS POKEMON");

        jMenu7.setText("File");
        jMenu5.add(jMenu7);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CharizardIMG)
                                    .addComponent(Charizard))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BlazikenIMG)
                                    .addComponent(Blaziken)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Umbreon)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(UmbreonIMG)))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Skarmory)
                                    .addComponent(SkarmoryIMG))))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Piplup))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(PiplupIMG))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RaikouIMG)
                                    .addComponent(Raikou))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Gardevoir)
                                            .addComponent(GardevoirIMG)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(SnorlaxIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(VaporeonIMG))
                                    .addComponent(Vaporeon)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CacturneIMG)
                                        .addComponent(Cacturne)
                                        .addComponent(BotonFinalizar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(Snorlax))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CharizardIMG)
                            .addComponent(PiplupIMG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SnorlaxIMG, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VaporeonIMG, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Charizard)
                            .addComponent(Blaziken)
                            .addComponent(Piplup)
                            .addComponent(Snorlax)
                            .addComponent(Vaporeon)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BlazikenIMG)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UmbreonIMG)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RaikouIMG)
                                .addComponent(SkarmoryIMG))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CacturneIMG)
                                    .addComponent(GardevoirIMG))
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gardevoir)
                    .addComponent(Raikou)
                    .addComponent(Cacturne)
                    .addComponent(Skarmory)
                    .addComponent(Umbreon))
                .addGap(48, 48, 48)
                .addComponent(BotonFinalizar)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PiplupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiplupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PiplupActionPerformed

    private void SkarmoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkarmoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SkarmoryActionPerformed

    private void RaikouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaikouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RaikouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Blaziken;
    private javax.swing.JLabel BlazikenIMG;
    private javax.swing.JButton BotonFinalizar;
    private javax.swing.JCheckBox Cacturne;
    private javax.swing.JLabel CacturneIMG;
    private javax.swing.JCheckBox Charizard;
    private javax.swing.JLabel CharizardIMG;
    private javax.swing.JCheckBox Gardevoir;
    private javax.swing.JLabel GardevoirIMG;
    private javax.swing.JCheckBox Piplup;
    private javax.swing.JLabel PiplupIMG;
    private javax.swing.JCheckBox Raikou;
    private javax.swing.JLabel RaikouIMG;
    private javax.swing.JCheckBox Skarmory;
    private javax.swing.JLabel SkarmoryIMG;
    private javax.swing.JCheckBox Snorlax;
    private javax.swing.JLabel SnorlaxIMG;
    private javax.swing.JCheckBox Umbreon;
    private javax.swing.JLabel UmbreonIMG;
    private javax.swing.JCheckBox Vaporeon;
    private javax.swing.JLabel VaporeonIMG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
